name = "unchartedterritory-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend/dist"

[build]
command = "cd frontend && npm install && npm run build"
cwd = "."

[build.upload]
format = "modules"
dir = "frontend/dist"
main = "./index.js"