name = "unchartedterritory-frontend"
main = "src/frontend-worker.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "frontend/dist"
entry-point = "workers-site"

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "static_content"
preview_id = "static_content_preview"

[build]
command = "cd frontend && npm install && npm run build"