name = "unchartedterritory-frontend"
main = "src/frontend-worker.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./frontend/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = true