name = "unchartedterritory-frontend"
main = "src/frontend-worker.ts"
compatibility_date = "2024-09-19"

[assets]
directory = "./frontend/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"