name = "unchartedterritory-frontend"
main = "src/frontend-worker.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "frontend/dist"

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "unchartedterritory_static"
preview_id = "unchartedterritory_static_preview"