name = "unchartedterritory-backend"
main = "dist/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Durable Object bindings for game session management
[[durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSession"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameSession"]

[env.staging]
name = "unchartedterritory-backend-staging"

# Durable Object bindings for staging
[[env.staging.durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSession"

[env.production]
name = "unchartedterritory-backend"

# Durable Object bindings for production
[[env.production.durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSession"