name: Playwright Tests

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json
        
    - name: Cache backend node_modules
      uses: actions/cache@v4
      with:
        path: backend/node_modules
        key: backend-deps-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          backend-deps-
          
    - name: Cache frontend node_modules
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: frontend-deps-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          frontend-deps-
          
    - name: Check if Playwright browsers exist locally
      id: check-browsers
      run: |
        if [ -d ~/.cache/ms-playwright ] && [ "$(ls -A ~/.cache/ms-playwright)" ]; then
          echo "browsers-exist=true" >> $GITHUB_OUTPUT
          echo "✅ Playwright browsers found in local cache"
        else
          echo "browsers-exist=false" >> $GITHUB_OUTPUT
          echo "❌ Playwright browsers not found, will install"
        fi
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci --prefer-offline
      
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci --prefer-offline
      
    - name: Install Playwright Browsers (conditional)
      if: steps.check-browsers.outputs.browsers-exist == 'false'
      run: |
        echo "Installing Playwright browsers..."
        npx playwright install --with-deps chromium
        echo "✅ Playwright browsers installed successfully"
      
    - name: Start backend server
      working-directory: ./backend
      run: |
        npm run dev &
        sleep 10
        
    - name: Start frontend server
      working-directory: ./frontend
      run: |
        npx wrangler dev --port 8787 &
        sleep 10
        
    - name: Run Playwright tests
      working-directory: ./frontend
      run: npx playwright test
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30