name: Playwright Tests

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json
        
    - name: Cache backend node_modules
      uses: actions/cache@v4
      with:
        path: backend/node_modules
        key: backend-deps-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          backend-deps-
          
    - name: Cache frontend node_modules
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: frontend-deps-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          frontend-deps-
          
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          playwright-browsers-
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci --prefer-offline
      
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci --prefer-offline
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
      
    - name: Start backend server
      working-directory: ./backend
      run: |
        npm run dev &
        sleep 10
        
    - name: Start frontend server
      working-directory: ./frontend
      run: |
        npx wrangler dev --port 8787 &
        sleep 10
        
    - name: Run Playwright tests
      working-directory: ./frontend
      run: npx playwright test
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30